# Environment configuration
environment:
  model_path: "src/environment/tactile_sensor.xml"
  max_steps: 300
  voxel_size: 0.01
  num_tactile_sensors: 14
  max_points: 1024

# Training configuration
training:
  n_envs: 8
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: 0.015
  total_timesteps: 10000000
  eval_freq: 10000
  
  # Directories
  save_dir: "models/saved"
  log_dir: "logs"
  tensorboard_log: "logs/tensorboard"

# Model configuration
model:
  pointnet:
    feature_transform: true
    dropout: 0.3
    
  policy:
    tactile_encoder:
      hidden_dims: [256, 128]
    pose_encoder:
      hidden_dims: [32, 32]
    action_encoder:
      hidden_dims: [32, 32]
    combined_encoder:
      hidden_dims: [256, 128]
    policy_head:
      hidden_dims: [64]
    value_head:
      hidden_dims: [64] 